# Generated by Django 4.2.4 on 2024-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='highest_bidder',
        ),
    ]
